### PR TITLE
Feature: Ledger client to Rust SDK

### PR DESCRIPTION
**Pull request by napalmpapalam**
## Feature: Ledger Client to Rust SDK

This PR part of the feature: [Configurable Ledger Client [banking-demo#236]](https://github.com/m10io/banking-demo/pull/236) and particularly referred to the [[mono#5833]](https://github.com/m10io/mono/pull/5833)

### Added
- gPRC and http implementation
- `tokio-stream`, `tokio`, `tokio-tungstenite` dependencies as the part of `client` feature, to observe the ledger via the WebSocket

### Changed
- Merged SDK `ledger_client` and `M10Client` into one trait object

### CODE REVIEW

**Comment by michael-wit** [comment]
I'm still confused why this needs to be done manually and not why our release tool:
[https://github.com/m10io/mono/tree/develop/tools/dev#readme](https://github.com/m10io/mono/tree/develop/tools/dev#readme)

**Comment by napalmpapalam** [comment]
> I'm still confused why this needs to be done manually and not via our release tool: https://github.com/m10io/mono/tree/develop/tools/dev#readme @shaynekellyii : Is this still working?

I didn't notice that there was such a tool. So I just have to move my WebSocket changes into the mono-repo and then I have to publish sdk via this tool?

**Comment by michael-wit** [comment]
> I didn't notice that there was such a tool. So I just have to move my WebSocket changes into the mono-repo and then I have to publish sdk via this tool?

Yes, correct, that's the way 😉.  Shayne has done this in the past, he should be able to walk you through.

**Comment by napalmpapalam** [comment]
Closing due to https://github.com/m10io/sdk/pull/3#issuecomment-1925470383, related changes moved into [[mono#5881]](https://github.com/m10io/mono/pull/5881)

**Comment by napalmpapalam** [comment]
Closing due to https://github.com/m10io/sdk/pull/3#issuecomment-1925470383, related changes moved into [[mono#5881]](https://github.com/m10io/mono/pull/5881)

**Pull request closed without merging**
